#!/usr/bin/env python3
"""
Analyse the Task S buffer sweep and write the results document.

QUESTION. The two parameterisations in taskS_symmetric.csv both fail the
validity check rho(clock_r, CV) < 0, so "is a valid Clock metric
reachable at ANY buffer length?" was still open -- and the paper's
central argument depends on the answer.

DESIGN. One variable. RHIST_LEN is fixed at 120 across all arms, so every
arm estimates the autocorrelation from the same number of samples with
the same maximum searched lag (half the buffer); only the span in ticks
varies, via RHIST_EVERY in {10, 50, 100, 200}. Reported as a curve over
all four arms, not as a search terminated when one passed.

MULTIPLICITY. The initial sweep (seeds 0-39) gave the widest arm
p = 0.0163 against a Bonferroni threshold of 0.05/4 = 0.0125, so it did
not survive correction. The arm was therefore re-run on 40 fresh seeds
(40-79) as an out-of-sample confirmation; that test is reported
separately and is not multiplicity-corrected because it is a single
pre-specified test of a directional prediction made before it was run.

Inputs:  results_v6/taskS_buffer_sweep.csv    (seeds 0-39, four arms)
         results_v6/taskS_buffer_confirm.csv  (seeds 40-79, widest arm)
Output:  paper/v6_supplement/taskS_buffer_sweep_RESULTS.md
"""
import csv
from pathlib import Path

import numpy as np
from scipy import stats

ROOT = Path(__file__).parent
SWEEP = ROOT / "results_v6" / "taskS_buffer_sweep.csv"
CONFIRM = ROOT / "results_v6" / "taskS_buffer_confirm.csv"
OUT = ROOT / "paper" / "v6_supplement" / "taskS_buffer_sweep_RESULTS.md"

ALPHA = 0.05


def arm_stats(rs):
    cr = np.array([float(r["ss_clock_r"]) for r in rs if r["ss_clock_r"] != ""])
    cv = np.array([float(r["ss_cv"]) for r in rs if r["ss_clock_r"] != ""])
    rho, p = stats.spearmanr(cr, cv) if len(cr) >= 3 else (np.nan, np.nan)
    d = [int(r["def_clock_r"]) for r in rs if int(r["def_clock_r"]) >= 0]
    T = np.median([float(r["T_div"]) for r in rs if r["T_div"]])
    return dict(n=len(cr), rho=float(rho), p=float(p),
                dmed=float(np.median(d)) if d else float("nan"), ndef=len(d),
                buf=int(rs[0]["buffer_ticks"]), T=float(T))


def main():
    rows = list(csv.DictReader(open(SWEEP)))
    arms = sorted({r["variant"] for r in rows}, key=lambda v: int(v[3:]))
    st = {v: arm_stats([r for r in rows if r["variant"] == v]) for v in arms}
    k = len(arms)
    bonf = ALPHA / k

    conf = arm_stats(list(csv.DictReader(open(CONFIRM))))

    defS = np.median([int(r["def_S"]) for r in rows if int(r["def_S"]) >= 0])
    defCV = np.median([int(r["def_CV"]) for r in rows if int(r["def_CV"]) >= 0])

    L = []
    A = L.append
    A("# v6 Task S — buffer sweep: is a valid Clock metric reachable?\n")
    A("Generated by `analysis_v6_taskS_sweep.py` from")
    A("`results_v6/taskS_buffer_sweep.csv` and")
    A("`results_v6/taskS_buffer_confirm.csv`.\n")
    A("Both parameterisations in the main Task S run fail the validity")
    A("check, so this sweep asks whether *any* buffer length yields a")
    A("`clock_r` that actually measures division regularity. One variable")
    A("only: sample count fixed at 120, span varied.\n")
    A(f"Runs: {k} arms x 40 seeds, 40,000 ticks each, 1D engine.\n")

    A("## The curve\n")
    A("Validity requires rho(clock_r, CV) to be **negative** (more regular")
    A("-> higher autocorrelation -> lower CV) and significant.\n")
    A("| buffer (ticks) | periods spanned | defined at tick | rho | p | valid |")
    A("|---|---|---|---|---|---|")
    for v in arms:
        s = st[v]
        ok = s["rho"] < 0 and s["p"] < bonf
        A(f"| {s['buf']:,} | {s['buf']/s['T']:.2f} | {s['dmed']:,.0f} "
          f"| {s['rho']:+.4f} | {s['p']:.4f} | {'**yes**' if ok else 'no'} |")
    A("")
    A(f"Bonferroni threshold over {k} arms: p < {bonf:.4f}.\n")

    A("Two features of this table carry the argument.\n")
    A("**Definedness equals buffer length exactly**, in every arm. This is")
    A("not an empirical finding but an identity: `clock_r` is defined the")
    A("moment a cell's history buffer fills, so its definedness time *is*")
    A("the buffer span. Whatever span validity demands is therefore also")
    A("the earliest the metric can exist.\n")
    A("**The approach to validity is not monotone.** The 2.36-period arm")
    A(f"returns rho = {st[arms[1]]['rho']:+.4f} — the *wrong sign* — and the")
    A(f"4.71-period arm {st[arms[2]]['rho']:+.4f}, indistinguishable from")
    A("zero. Only the widest arm separates from noise. We therefore do not")
    A("claim a smooth relationship between span and validity; at n = 40 the")
    A("intermediate arms are simply uninformative.\n")

    wide = st[arms[-1]]
    A("## Out-of-sample confirmation\n")
    A(f"The widest arm was selected on seeds 0-39 with p = {wide['p']:.4f},")
    A(f"which does **not** clear the Bonferroni threshold of {bonf:.4f}. A")
    A("borderline, multiplicity-uncorrected result is not an acceptable")
    A("basis for this paper's central claim, so the arm was re-run on 40")
    A("seeds it had never been evaluated on.\n")
    A(f"| set | seeds | n | rho | p |")
    A("|---|---|---|---|---|")
    A(f"| selection | 0-39 | {wide['n']} | {wide['rho']:+.4f} | {wide['p']:.5f} |")
    A(f"| confirmation | 40-79 | {conf['n']} | {conf['rho']:+.4f} | {conf['p']:.5f} |")
    A("")
    A(f"The confirmation is a single pre-specified test of a directional")
    A(f"prediction, so it needs no correction: rho = {conf['rho']:+.4f},")
    A(f"p = {conf['p']:.5f}. `clock_r` became defined at tick")
    A(f"{conf['dmed']:,.0f} in {conf['ndef']}/40 runs.\n")

    A("## What this establishes\n")
    A(f"A `clock_r` that measurably tracks division regularity requires a")
    A(f"buffer of about {wide['buf']/wide['T']:.1f} division periods")
    A(f"(~{wide['buf']:,} ticks at a median period of {wide['T']:,.0f}).")
    A("Because definedness equals buffer length, that is also the earliest")
    A("tick at which a valid Clock reading can exist.\n")
    A("| metric | defined at | ratio to S |")
    A("|---|---|---|")
    A(f"| S (Map), spatial correlation | {defS:,.0f} | — |")
    A(f"| CV (original Clock) | {defCV:,.0f} | {defCV/defS:.0f}x |")
    A(f"| clock_r, **valid** parameterisation | **{wide['buf']:,}** | "
      f"**{wide['buf']/defS:.0f}x** |")
    A("")
    A("The redesign was built specifically to remove the definedness floor")
    A("that produced defect 3. Made valid, it does not merely fail to")
    A(f"remove the floor — it raises it, from {defCV:,.0f} ticks to")
    A(f"{wide['buf']:,}, a factor of {wide['buf']/defS:.0f} above the")
    A("spatial metric rather than the original 30x.\n")
    A("This is the quantitative form of the time-frequency constraint. A")
    A("regularity statistic needs several periods of the process it")
    A("describes; a spatial correlation needs one field relaxation time")
    A("(~40 ticks) and is defined by ~150. No estimator choice closes a")
    A("gap of that size, because the gap is the ratio of the two")
    A("phenomena's intrinsic timescales.\n")
    A("**Caveat, stated plainly.** At a 24,000-tick buffer in a")
    A("40,000-tick run, `clock_r` is an average over cells that have lived")
    A("24,000 ticks — founder-lineage cells only, since daughters start")
    A("with an empty buffer (`Cell.create`, `age = 0`) while mothers retain")
    A("theirs. The valid measurement is therefore made on an age-selected")
    A("subpopulation. This does not rescue the metric: a cell too young to")
    A("have a full buffer is exactly a cell whose period has not yet been")
    A("observed. The selection restates the constraint rather than")
    A("concealing it.\n")
    A("---\n")
    A("Raw data: `results_v6/taskS_buffer_sweep.csv`, ")
    A("`results_v6/taskS_buffer_confirm.csv`. ")
    A("Regenerate: `python3 analysis_v6_taskS_sweep.py`.")

    OUT.write_text("\n".join(L) + "\n")
    print("\n".join(L))
    print(f"\n[wrote {OUT}]")


if __name__ == "__main__":
    main()
